server:
  port: 81

spring:
  application:
    name: a.demo.com

  metrics:
    servo:
      enabled: false
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:4567
  zipkin:
    base-url: http://127.0.0.1:9411
  sleuth:
    sampler:
      probability: 1

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'


  metrics:
    tags:
      application: ${spring.application.name}


eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka


  instance:
      #instance-id: c
      #访问路径可以显示IP地址
      prefer-ip-address: true





