apiVersion: v1
kind: Service
metadata:
  name: c-demo-com-svc
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/scheme: "http"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "80"
  labels:
    app: c.demo.com
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: c.demo.com
